# Generated by Django 3.2.6 on 2022-10-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ['-id'], 'verbose_name': 'Cостав рецепта', 'verbose_name_plural': 'Состав рецепта'},
        ),
    ]
